//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DG_Tweening_EaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(DG.Tweening.Ease));
		L.RegVar("Unset", new LuaCSFunction(get_Unset), null);
		L.RegVar("Linear", new LuaCSFunction(get_Linear), null);
		L.RegVar("InSine", new LuaCSFunction(get_InSine), null);
		L.RegVar("OutSine", new LuaCSFunction(get_OutSine), null);
		L.RegVar("InOutSine", new LuaCSFunction(get_InOutSine), null);
		L.RegVar("InQuad", new LuaCSFunction(get_InQuad), null);
		L.RegVar("OutQuad", new LuaCSFunction(get_OutQuad), null);
		L.RegVar("InOutQuad", new LuaCSFunction(get_InOutQuad), null);
		L.RegVar("InCubic", new LuaCSFunction(get_InCubic), null);
		L.RegVar("OutCubic", new LuaCSFunction(get_OutCubic), null);
		L.RegVar("InOutCubic", new LuaCSFunction(get_InOutCubic), null);
		L.RegVar("InQuart", new LuaCSFunction(get_InQuart), null);
		L.RegVar("OutQuart", new LuaCSFunction(get_OutQuart), null);
		L.RegVar("InOutQuart", new LuaCSFunction(get_InOutQuart), null);
		L.RegVar("InQuint", new LuaCSFunction(get_InQuint), null);
		L.RegVar("OutQuint", new LuaCSFunction(get_OutQuint), null);
		L.RegVar("InOutQuint", new LuaCSFunction(get_InOutQuint), null);
		L.RegVar("InExpo", new LuaCSFunction(get_InExpo), null);
		L.RegVar("OutExpo", new LuaCSFunction(get_OutExpo), null);
		L.RegVar("InOutExpo", new LuaCSFunction(get_InOutExpo), null);
		L.RegVar("InCirc", new LuaCSFunction(get_InCirc), null);
		L.RegVar("OutCirc", new LuaCSFunction(get_OutCirc), null);
		L.RegVar("InOutCirc", new LuaCSFunction(get_InOutCirc), null);
		L.RegVar("InElastic", new LuaCSFunction(get_InElastic), null);
		L.RegVar("OutElastic", new LuaCSFunction(get_OutElastic), null);
		L.RegVar("InOutElastic", new LuaCSFunction(get_InOutElastic), null);
		L.RegVar("InBack", new LuaCSFunction(get_InBack), null);
		L.RegVar("OutBack", new LuaCSFunction(get_OutBack), null);
		L.RegVar("InOutBack", new LuaCSFunction(get_InOutBack), null);
		L.RegVar("InBounce", new LuaCSFunction(get_InBounce), null);
		L.RegVar("OutBounce", new LuaCSFunction(get_OutBounce), null);
		L.RegVar("InOutBounce", new LuaCSFunction(get_InOutBounce), null);
		L.RegVar("Flash", new LuaCSFunction(get_Flash), null);
		L.RegVar("InFlash", new LuaCSFunction(get_InFlash), null);
		L.RegVar("OutFlash", new LuaCSFunction(get_OutFlash), null);
		L.RegVar("InOutFlash", new LuaCSFunction(get_InOutFlash), null);
		L.RegVar("INTERNAL_Zero", new LuaCSFunction(get_INTERNAL_Zero), null);
		L.RegVar("INTERNAL_Custom", new LuaCSFunction(get_INTERNAL_Custom), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<DG.Tweening.Ease>.Check = CheckType;
		StackTraits<DG.Tweening.Ease>.Push = Push;
	}

	static void Push(IntPtr L, DG.Tweening.Ease arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_DG_Tweening_Ease = typeof(DG.Tweening.Ease);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_DG_Tweening_Ease, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Unset(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.Unset);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Linear(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.Linear);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InSine(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InSine);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutSine(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutSine);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutSine(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutSine);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InQuad(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InQuad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutQuad(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutQuad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutQuad(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutQuad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InCubic(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InCubic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutCubic(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutCubic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutCubic(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutCubic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InQuart(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InQuart);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutQuart(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutQuart);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutQuart(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutQuart);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InQuint(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InQuint);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutQuint(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutQuint);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutQuint(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutQuint);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InExpo(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InExpo);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutExpo(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutExpo);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutExpo(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutExpo);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InCirc(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InCirc);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutCirc(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutCirc);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutCirc(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutCirc);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InElastic(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InElastic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutElastic(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutElastic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutElastic(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutElastic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InBack(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InBack);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutBack(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutBack);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutBack(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutBack);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InBounce(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InBounce);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutBounce(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutBounce);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutBounce(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutBounce);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Flash(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.Flash);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InFlash(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InFlash);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OutFlash(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.OutFlash);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InOutFlash(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.InOutFlash);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_INTERNAL_Zero(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.INTERNAL_Zero);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_INTERNAL_Custom(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.Ease.INTERNAL_Custom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		DG.Tweening.Ease o = (DG.Tweening.Ease)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

