//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Platform_PlatformNameWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Sango.Platform.PlatformName));
		L.RegVar("Android", new LuaCSFunction(get_Android), null);
		L.RegVar("Ios", new LuaCSFunction(get_Ios), null);
		L.RegVar("Window", new LuaCSFunction(get_Window), null);
		L.RegVar("Mac", new LuaCSFunction(get_Mac), null);
		L.RegVar("Webgl", new LuaCSFunction(get_Webgl), null);
		L.RegVar("Webgl_wechat", new LuaCSFunction(get_Webgl_wechat), null);
		L.RegVar("Webgl_tiktok", new LuaCSFunction(get_Webgl_tiktok), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<Sango.Platform.PlatformName>.Check = CheckType;
		StackTraits<Sango.Platform.PlatformName>.Push = Push;
	}

	static void Push(IntPtr L, Sango.Platform.PlatformName arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_Sango_Platform_PlatformName = typeof(Sango.Platform.PlatformName);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_Sango_Platform_PlatformName, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Android(IntPtr L)
	{
		ToLua.Push(L, Sango.Platform.PlatformName.Android);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Ios(IntPtr L)
	{
		ToLua.Push(L, Sango.Platform.PlatformName.Ios);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Window(IntPtr L)
	{
		ToLua.Push(L, Sango.Platform.PlatformName.Window);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Mac(IntPtr L)
	{
		ToLua.Push(L, Sango.Platform.PlatformName.Mac);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Webgl(IntPtr L)
	{
		ToLua.Push(L, Sango.Platform.PlatformName.Webgl);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Webgl_wechat(IntPtr L)
	{
		ToLua.Push(L, Sango.Platform.PlatformName.Webgl_wechat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Webgl_tiktok(IntPtr L)
	{
		ToLua.Push(L, Sango.Platform.PlatformName.Webgl_tiktok);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		Sango.Platform.PlatformName o = (Sango.Platform.PlatformName)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

