//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_GameWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.Game), typeof(Sango.App<Sango.Game.Game>));
		L.RegFunction("Init", new LuaCSFunction(Init));
		L.RegFunction("Shutdown", new LuaCSFunction(Shutdown));
		L.RegFunction("Pause", new LuaCSFunction(Pause));
		L.RegFunction("Resume", new LuaCSFunction(Resume));
		L.RegFunction("EnterMapEditor", new LuaCSFunction(EnterMapEditor));
		L.RegFunction("StartNewGame", new LuaCSFunction(StartNewGame));
		L.RegFunction("StartGame", new LuaCSFunction(StartGame));
		L.RegFunction("Update", new LuaCSFunction(Update));
		L.RegFunction("DebugAI", new LuaCSFunction(DebugAI));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_Game));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_Game(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.Game obj = new Sango.Game.Game();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.Game.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			UnityEngine.MonoBehaviour arg0 = (UnityEngine.MonoBehaviour)ToLua.CheckObject<UnityEngine.MonoBehaviour>(L, 2);
			Sango.Platform.PlatformName arg1 = (Sango.Platform.PlatformName)ToLua.CheckObject(L, 3, TypeTraits<Sango.Platform.PlatformName>.type);
			obj.Init(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Shutdown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			obj.Shutdown();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Pause(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			obj.Pause();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Resume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			obj.Resume();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EnterMapEditor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			obj.EnterMapEditor();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartNewGame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			obj.StartNewGame();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartGame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.StartGame(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Game obj = (Sango.Game.Game)ToLua.CheckObject<Sango.Game.Game>(L, 1);
			obj.Update();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DebugAI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Sango.Game.Game.DebugAI();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

