//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_GameStateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.GameState), typeof(Sango.Singletion<Sango.Game.GameState>));
		L.RegFunction("GetCurState", new LuaCSFunction(GetCurState));
		L.RegFunction("ChangeState", new LuaCSFunction(ChangeState));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_GameState));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_GameState(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.GameState obj = new Sango.Game.GameState();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.GameState.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.GameState obj = (Sango.Game.GameState)ToLua.CheckObject<Sango.Game.GameState>(L, 1);
			int o = obj.GetCurState();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.GameState obj = (Sango.Game.GameState)ToLua.CheckObject<Sango.Game.GameState>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.ChangeState(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

