//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_System_Sango_PoolManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.System<Sango.PoolManager>), typeof(Sango.Module), "System_Sango_PoolManager");
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("Instance", new LuaCSFunction(get_Instance), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Sango.System<Sango.PoolManager>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

