//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_GameVariablesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GameVariables");
		L.RegVar("TroopMoveSpeed", new LuaCSFunction(get_TroopMoveSpeed), new LuaCSFunction(set_TroopMoveSpeed));
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TroopMoveSpeed(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushnumber(L, Sango.Game.GameVariables.TroopMoveSpeed);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TroopMoveSpeed(IntPtr L)
	{
		try
		{
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			Sango.Game.GameVariables.TroopMoveSpeed = arg0;
			Sango.Game.GameVariables.TroopMoveSpeed = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

