//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Singletion_Sango_AssetBundleManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Singletion<Sango.AssetBundleManager>), typeof(System.Object), "Singletion_Sango_AssetBundleManager");
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("Instance", new LuaCSFunction(get_Instance), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Sango.Singletion<Sango.AssetBundleManager>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

