//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ShadowQualityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ShadowQuality));
		L.RegVar("Disable", new LuaCSFunction(get_Disable), null);
		L.RegVar("HardOnly", new LuaCSFunction(get_HardOnly), null);
		L.RegVar("All", new LuaCSFunction(get_All), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.ShadowQuality>.Check = CheckType;
		StackTraits<UnityEngine.ShadowQuality>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.ShadowQuality arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_ShadowQuality = typeof(UnityEngine.ShadowQuality);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_ShadowQuality, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Disable(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ShadowQuality.Disable);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HardOnly(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ShadowQuality.HardOnly);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_All(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ShadowQuality.All);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.ShadowQuality o = (UnityEngine.ShadowQuality)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

