//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ShadowProjectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ShadowProjection));
		L.RegVar("CloseFit", new LuaCSFunction(get_CloseFit), null);
		L.RegVar("StableFit", new LuaCSFunction(get_StableFit), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.ShadowProjection>.Check = CheckType;
		StackTraits<UnityEngine.ShadowProjection>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.ShadowProjection arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_ShadowProjection = typeof(UnityEngine.ShadowProjection);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_ShadowProjection, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CloseFit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ShadowProjection.CloseFit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StableFit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ShadowProjection.StableFit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.ShadowProjection o = (UnityEngine.ShadowProjection)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

