//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_GUI_ToolbarButtonSizeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.GUI.ToolbarButtonSize));
		L.RegVar("Fixed", new LuaCSFunction(get_Fixed), null);
		L.RegVar("FitToContents", new LuaCSFunction(get_FitToContents), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.GUI.ToolbarButtonSize>.Check = CheckType;
		StackTraits<UnityEngine.GUI.ToolbarButtonSize>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.GUI.ToolbarButtonSize arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_GUI_ToolbarButtonSize = typeof(UnityEngine.GUI.ToolbarButtonSize);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_GUI_ToolbarButtonSize, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Fixed(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.GUI.ToolbarButtonSize.Fixed);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FitToContents(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.GUI.ToolbarButtonSize.FitToContents);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.GUI.ToolbarButtonSize o = (UnityEngine.GUI.ToolbarButtonSize)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

